version: "3.7"

services:

  test:
    env_file:
      - ./env/.env.db.dev
      - ./env/.env.dev
    entrypoint: "/entrypoint.d/wait_for_postgres.sh"
    # TODO: xdist doesn't play nice with session scoped fixtures
    command: "python -m pytest -s -v"
