version: "3.7"

x-services:

  monitor:
    &monitor
    build:
      dockerfile: ./docker/Dockerfile
      context: .
      args:
        - PROJECT_ROOT=${PROJECT_ROOT}
        - MONITOR_USER=${MONITOR_USER}
        - MONITOR_GROUP=${MONITOR_GROUP}
        - UID=${UID}
        - GID=${GID}
    volumes:
      - ./monitor/:${PROJECT_ROOT}

services:

  producer:
    <<: *monitor
    container_name: "producer"

  consumer:
    <<: *monitor
    container_name: "consumer"

  test:
    <<: *monitor
    container_name: "test"
