version: "3.7"

volumes:
  postgres_data:

services:

  db:
    image: postgres:12.0-alpine
    container_name: "$DB_CONTAINER_NAME"
    env_file:
      - ./env/.env.db.dev
    expose:
      - "$DB_PORT"
    ports:
      - "$DB_HOST_PORT:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
